### ISSUE TITLE
Lorien ignores bindings from keyd-application-mapper

### ISSUE THREAD

**Issue by i-c-u-p** [rvaiya/keyd#181]
Application bindings set for [Lorien](https://github.com/mbrlabs/Lorien) in `~/.config/app.conf` don't work when keyd-application-mapper is running, even though the window is detected. Lorien was installed from the AUR package [lorien-bin](https://aur.archlinux.org/packages/lorien-bin). When a Lorien window is in focus, it shows up in keyd-application-mapper's logs as `Active window: lorien|lorien-v0-4-0`.

Here's my configs:

~/.config/keyd/app.conf:

```
[alacritty]
extend.i = S-pagedown
extend.o = S-pageup

[alacritty|htop]
extend.i = pagedown
extend.o = pageup

[lorien]
extend+shift.b = C-y
```

<details>
<summary>
/etc/keyd/default.conf:
</summary>

```
[ids]
*

# Colemak-DH (Curl+Angle mods)
[main]
esc = overload(switch, capslock)
capslock = overload(extend, esc)
rightmeta = compose
rightcontrol = rightcontrol
rightshift = rightshift
e = f
r = p
t = b
y = j
u = l
i = u
o = y
p = ;
s = r
d = s
f = t
h = m
j = n
k = e
l = i
; = o
z = x
x = c
c = d
b = z
n = k
m = h

[qwerty]
esc = overload(switch, capslock)
capslock = overload(extend, esc)
rightmeta = compose
rightcontrol = rightcontrol
rightshift = rightshift
e = e
r = r
t = t
y = y
u = u
i = i
o = o
p = p
s = s
d = d
f = f
h = h
j = j
k = k
l = l
; = ;
z = z
x = x
c = c
b = b
n = n
m = m

[noCapsLayer]
capslock = esc

[extend:C]
j = left
k = down
l = up
; = right
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
- = f11
= = f12
m = home
/ = end
i = pagedown
o = pageup
f = backspace
r = delete
s = layer(alt)
d = layer(shift)
space = layer(control)
g = enter

[extend+control]
s = layer(alt)
d = layer(shift)

[extend+shift]
space = layer(control)
s = layer(alt)

[extend+alt]
d = layer(shift)
space = layer(control)

[extend+control+shift]
s = layer(alt)

[extend+control+alt]
d = layer(shift)

[extend+shift+alt]
space = layer(control)

[extend+control+shift+alt]

[switch]
q = toggle(qwerty)
w = toggle(noCapsLayer)
```

</details>

**Comment by rvaiya** [comment]
Can you post the output of `KEYD_DEBUG=1 keyd-application-mapper` under the latest commit?

**Comment by i-c-u-p** [comment]
> Can you post the output of `KEYD_DEBUG=1 keyd-application-mapper` using the latest commit?

```
$ keyd -v
keyd v2.3.1-rc (763edac)
$ KEYD_DEBUG=1 keyd-application-mapper
X detected
Active window: lorien|lorien-v0-4-0
DEBUG: src/keyd.c:454: Debug mode activated
Active window: alacritty|keyd-debug-1-keyd-application-mapper
DEBUG: src/keyd.c:454: Debug mode activated
Active window: lorien|lorien-v0-4-0
DEBUG: src/keyd.c:454: Debug mode activated
Active window: mousepad|config-keyd-app-conf-mousepad
DEBUG: src/keyd.c:454: Debug mode activated
Active window: lorien|lorien-v0-4-0
DEBUG: src/keyd.c:454: Debug mode activated
Active window: alacritty|keyd-debug-1-keyd-application-mapper
DEBUG: src/keyd.c:454: Debug mode activated
```

**Comment by rvaiya** [comment]
It looks like the rule is being matched correctly. What is the output of `keyd -m` after pressing `capslock+shift+b` while lorien is focused?

**Comment by i-c-u-p** [comment]
> It looks like the rule is being matched correctly. What is the output of `keyd -m` after pressing `capslock+shift+b` while lorien is focused?

output of <kbd>capslock+s+b</kbd>:
```
$ sudo keyd -m
device added: 0fac:0ade (keyd virtual device)
device added: 1b1c:1b33 (<redacted keyboard name>  Keyboard)
device added: 046d:4051 (<redacted mouse name>)
keyd virtual device	0fac:0ade	enter up
<redacted mouse name>	046d:4051	leftmouse down
<redacted mouse name>	046d:4051	leftmouse up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	leftshift up
keyd virtual device	0fac:0ade	y down
keyd virtual device	0fac:0ade	y up
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	leftshift up
keyd virtual device	0fac:0ade	leftcontrol up
```
output of <kbd>capslock+leftshift+b</kbd>:
```
$ sudo keyd -m
device added: 0fac:0ade (keyd virtual device)
device added: 1b1c:1b33 (<redacted keyboard name>  Keyboard)
device added: 046d:4051 (<redacted mouse name>)
keyd virtual device	0fac:0ade	enter up
<redacted mouse name>	046d:4051	leftmouse down
<redacted mouse name>	046d:4051	leftmouse up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	leftshift up
keyd virtual device	0fac:0ade	y down
keyd virtual device	0fac:0ade	y up
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	leftshift up
keyd virtual device	0fac:0ade	leftcontrol up
```

While pressing the <kbd>capslock+leftshift+b</kbd> bind repeatedly during testing, the <kbd>C-y</kbd> binding actually did occasionally activate in Lorien, but it happens randomly and I can't reliably reproduce it other than mashing <kbd>capslock+leftshift+b</kbd> until it does.

**Comment by i-c-u-p** [comment]
> It looks like the rule is being matched correctly. What is the output of `keyd -m` after pressing `capslock+shift+b` while lorien is focused?

output of <kbd>capslock+s+b</kbd>:
```
$ sudo keyd -m
device added: 0fac:0ade (keyd virtual device)
device added: <redacted keyboard id> (<redacted keyboard name>  Keyboard)
device added: <redacted mouse id> (<redacted mouse name>)
keyd virtual device	0fac:0ade	enter up
<redacted mouse name>	<redacted mouse id>	leftmouse down
<redacted mouse name>	<redacted mouse id>	leftmouse up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	leftshift up
keyd virtual device	0fac:0ade	y down
keyd virtual device	0fac:0ade	y up
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	leftshift up
keyd virtual device	0fac:0ade	leftcontrol up
```
output of <kbd>capslock+leftshift+b</kbd>:
```
$ sudo keyd -m
device added: 0fac:0ade (keyd virtual device)
device added: <redacted keyboard id> (<redacted keyboard name>  Keyboard)
device added: <redacted mouse id> (<redacted mouse name>)
keyd virtual device	0fac:0ade	enter up
<redacted mouse name>	<redacted mouse id>	leftmouse down
<redacted mouse name>	<redacted mouse id>	leftmouse up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	leftshift up
keyd virtual device	0fac:0ade	y down
keyd virtual device	0fac:0ade	y up
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	leftshift up
keyd virtual device	0fac:0ade	leftcontrol up
```

While pressing the <kbd>capslock+leftshift+b</kbd> bind repeatedly during testing, the <kbd>C-y</kbd> binding actually did occasionally activate in Lorien, but it happens randomly and I can't reliably reproduce it other than mashing <kbd>capslock+leftshift+b</kbd> until it does.

**Comment by rvaiya** [comment]
It looks like keyd is emitting the correct keycodes. My suspicion is that lorien doesn't like the additional `leftshift` events. Try a simpler binding like `- = C-y` and see if it works consistently.

**Comment by i-c-u-p** [comment]
> It looks like keyd is emitting the correct keycodes. My suspicion is that lorien doesn't like the additional `leftshift` events. Try a simpler binding like `- = C-y` and see if it works consistently.

Changing the binding hitting <kbd>-</kbd> results in the same problem. Here's the output log (along with <kbd>C-y</kbd> which does work):

app.conf (Lorien section):
```
[lorien]
- = C-y
```
output of pressing <kbd>-</kbd> on keyboard:
```
$ keyd -v
keyd v2.3.1-rc (9325bf3)
$ sudo keyd -m
device added: 0fac:0ade (keyd virtual device)
device added: <keyboard id> (<keyboard name>  Keyboard)
device added: <mouse id> (<mouse name>)
keyd virtual device	0fac:0ade	enter up
<mouse name>	<mouse id>	leftmouse down
<mouse name>	<mouse id>	leftmouse up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	y down
keyd virtual device	0fac:0ade	y up
keyd virtual device	0fac:0ade	leftcontrol up
```
output of pressing <kbd>C-y</kbd> on keyboard:
```
$ sudo keyd -m
device added: 0fac:0ade (keyd virtual device)
device added: <keyboard id> (<keyboard name>  Keyboard)
device added: <mouse id> (<mouse name>)
keyd virtual device	0fac:0ade	enter up
<mouse name>	<mouse id>	leftmouse down
<mouse name>	<mouse id>	leftmouse up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	y down
keyd virtual device	0fac:0ade	y up
keyd virtual device	0fac:0ade	leftcontrol up
```

**Comment by rvaiya** [comment]
Can you try this using the test branch? (e.g `git fetch origin; git checkout origin/test; make && sudo make install`)

**Comment by i-c-u-p** [comment]
> Can you try the tip of test again? I believe this should do the trick.

That fixed it. Output log:

Pressing <kbd>-</kbd>:

```
$ keyd -v
keyd v2.3.1-rc (6c4c6ac)
$ sudo keyd -m
device added: 0fac:0ade (keyd virtual device)
device added: <keyboard id> (<keyboard name>  Keyboard)
device added: <mouse id> (<mouse name>)
keyd virtual device	0fac:0ade	enter up
<mouse name>	<mouse id>	leftmouse down
<mouse name>	<mouse id>	leftmouse up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	y down
keyd virtual device	0fac:0ade	y up
keyd virtual device	0fac:0ade	leftcontrol up
```

Pressing <kbd>capslock+d+b</kbd> (after changing `[lorien]` section of app.conf back to `extend+shift.b = C-y`):
```
$ sudo keyd -m
device added: 0fac:0ade (keyd virtual device)
device added: <keyboard id> (<keyboard name>  Keyboard)
device added: <mouse id> (<mouse name>)
keyd virtual device	0fac:0ade	enter up
<mouse name>	<mouse id>	leftmouse down
<mouse name>	<mouse id>	leftmouse up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	leftshift up
keyd virtual device	0fac:0ade	y down
keyd virtual device	0fac:0ade	y up
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	leftshift up
keyd virtual device	0fac:0ade	leftcontrol up
```

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.

**Comment by i-c-u-p** [comment]
The Lorien bindings work in the latest commit, but they still have a problem that I unfortunately forgot to mention earlier, which is that they don't repeat when held.

https://user-images.githubusercontent.com/96894903/163755558-1e5f5572-d885-42fc-a165-3180e86a47d3.mp4

In this demonstration video in Mousepad, you can see that when <kbd>capslock+b</kbd> is held, it outputs <kbd>C-z</kbd> with the delay and rate set in x (I actually set it in `xfce4-keyboard-settings`, but it's reflected in `xset q` (output below)) and when holding and releasing <kbd>d</kbd> ontop of <kbd>capslock+b</kbd> it switches between <kbd>C-z</kbd> and <kbd>C-s-z</kbd> with no delay, which appears up as the text appearing and disappearing in a sweeping motion in the video. But in Lorien when <kbd>capslock+b</kbd> or <kbd>capslock+d+b</kbd> are held, <kbd>C-z</kbd> and <kbd>C-s-z</kbd> don't repeat and so <kbd>b</kbd> has to be released and pressed repeatedly to input it multiple times. This happens in keyd versions a5e6a83 and 6c4c6ac. My configs have changed so I'll also include those again.

<details>
<summary>
"xset q" output:
</summary>

```
Keyboard Control:
  auto repeat:  on    key click percent:  0    LED mask:  00000002
  XKB indicators:
    00: Caps Lock:   off    01: Num Lock:    on     02: Scroll Lock: off
    03: Compose:     off    04: Kana:        off    05: Sleep:       off
    06: Suspend:     off    07: Mute:        off    08: Misc:        off
    09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
    12: Group 2:     off    13: Mouse Keys:  off
  auto repeat delay:  250    repeat rate:  50
  auto repeating keys:  00ffffffdffffbbf
                        fadfffefffedffff
                        9fffffffffffffff
                        fff7ffffffffffff
  bell percent:  50    bell pitch:  400    bell duration:  100
Pointer Control:
  acceleration:  2/1    threshold:  4
Screen Saver:
  prefer blanking:  no    allow exposures:  no
  timeout:  1200    cycle:  900
Colors:
  default colormap:  0x20    BlackPixel:  0x0    WhitePixel:  0xffffff
Font Path:
  /usr/share/fonts/misc,/usr/share/fonts/TTF,/usr/share/fonts/OTF,/usr/share/fonts/100dpi,/usr/share/fonts/75dpi,built-ins
DPMS (Energy Star):
  Standby: 1800    Suspend: 0    Off: 3600
  DPMS is Enabled
  Monitor is On
```

</details>

<details>
<summary>
~/.config/keyd/app.conf:
</summary>

```
[alacritty]
CapsLayer.i = S-pagedown
CapsLayer.o = S-pageup

[alacritty|htop]
CapsLayer.i = pagedown
CapsLayer.o = pageup

[lorien]
CapsLayer+shift.b = C-y

[gimp-2-10]
CapsLayer+shift.b = C-y
```

</details>

<details>
<summary>
/etc/keyd/default.conf:
</summary>

```
[ids]
*

# Colemak-DH (Curl+Angle mods)
[main]
esc = overload(LayoutLayer, capslock)
capslock = overload(CapsLayer, esc)
rightmeta = compose
rightcontrol = rightcontrol
rightshift = rightshift
e = f
r = p
t = b
y = j
u = l
i = u
o = y
p = ;
s = r
d = s
f = t
h = m
j = n
k = e
l = i
; = o
z = x
x = c
c = d
b = z
n = k
m = h

[QWERTY]
e = e
r = r
t = t
y = y
u = u
i = i
o = o
p = p
s = s
d = d
f = f
h = h
j = j
k = k
l = l
; = ;
z = z
x = x
c = c
b = b
n = n
m = m

[NoCapsLayer]
capslock = esc

[NumPrac]
a = tab
s = S-enter
d = C-backspace
f = backspace

[CapsLayer:C]
j = left
k = down
l = up
; = right
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
- = f11
= = f12
m = home
/ = end
i = pagedown
o = pageup
f = backspace
r = delete
space = layer(control)
s = layer(alt)
d = layer(shift)
g = enter

[CapsLayer+control]
s = layer(alt)
d = layer(shift)

[CapsLayer+shift]
space = layer(control)
s = layer(alt)

[CapsLayer+alt]
d = layer(shift)
space = layer(control)

[CapsLayer+control+shift]
s = layer(alt)

[CapsLayer+control+alt]
d = layer(shift)

[CapsLayer+shift+alt]
space = layer(control)

[CapsLayer+control+shift+alt]

[LayoutLayer]
q = toggle(QWERTY)
w = toggle(NoCapsLayer)
e = toggle(NumPrac)
```

</details>

**Comment by rvaiya** [comment]
Does this work without keyd? I would assume Lorien just doesn't implement key repeat.

**Comment by i-c-u-p** [comment]
> Does this work without keyd? I would assume Lorien just doesn't implement key repeat.

Yes; I guess it's just an issue with Lorien then. I probably should have checked that before making a long-winded comment about it...
I'll close the issue now since this is fixed.

**Comment by rvaiya** [comment]
I've enhanced macros to allow for timeouts to be specified between individual keys. This should allow you to make use of keyd's built in macro repeat functionality to achieve what you want.

Try mapping to something like `macro(leftcontrol+b+1ms)`. You may have to increase the timeout from `1ms`, depending on how long of a gap lorien expects.

**Comment by i-c-u-p** [comment]
> I've enhanced macros to allow for timeouts to be specified between individual keys. This should allow you to make use of keyd's built in macro repeat functionality to achieve what you want.
> 
> Try mapping to something like `macro(leftcontrol+b+1ms)`. You may have to increase the timeout from `1ms`, depending on how long of a gap lorien expects.

A delay around 12ms seems to be the fastest for Lorien macros. As it's set lower than that, Lorien starts missing progressively more inputs, which makes it slower.

As a side issue, I added `macro_timeout = 250` and `macro_repeat_timeout = 20` to my default.conf to try matching what appears in `xset -q`, and I think the repeat timeout isn't actually reached. According to `xset -q` my auto repeat delay is 250 and repeat rate is 50. I held down the <kbd>a</kbd> key for 4 seconds (approximately; I eyeballed it using my clock in xfce) twice and on average there were 185 a's. Then I did the same holding <kbd>capslock+a</kbd> with `CapsLayer.a = macro(a)` under the `[mousepad]` section in app.conf, and it averaged to 133.5 a's. This means the delay is only ~72.16% as fast as expected. I did the same test holding <kbd>capslock+s</kbd> with `CapsLayer.s = macro2(250, 20, a)` and that only produced 123 a's, ~66.49% of the expected amount.

As for the repeat delay set in `macro_timeout` and macro2(), I couldn't tell any difference by eye so a more rigorous method would be needed to check those.

<details>
<summary>
~/.config/keyd/app.conf:
</summary>

```
[alacritty]
CapsLayer.i = S-pagedown
CapsLayer.o = S-pageup

[alacritty|htop]
CapsLayer.i = pagedown
CapsLayer.o = pageup

[alacritty|man-*]
CapsLayer.i = pagedown
CapsLayer.o = pageup

[lorien]
CapsLayer.b = macro(leftcontrol+z+12ms)
CapsLayer+shift.b = macro(leftcontrol+y+12ms)

[gimp-2-10]
CapsLayer+shift.b = C-y
```

</details>

<details>
<summary>
/etc/keyd/default.conf:
</summary>

```
[ids]
*

[global]
macro_timeout = 250
macro_repeat_timeout = 20

# Colemak-DH (Curl+Angle mods)
[main]
esc = overload(LayoutLayer, capslock)
capslock = overload(CapsLayer, esc)
rightmeta = compose
rightcontrol = rightcontrol
rightshift = rightshift
e = f
r = p
t = b
y = j
u = l
i = u
o = y
p = ;
s = r
d = s
f = t
h = m
j = n
k = e
l = i
; = o
z = x
x = c
c = d
b = z
n = k
m = h

[QWERTY]
e = e
r = r
t = t
y = y
u = u
i = i
o = o
p = p
s = s
d = d
f = f
h = h
j = j
k = k
l = l
; = ;
z = z
x = x
c = c
b = b
n = n
m = m

[NoCapsLayer]
capslock = esc

[NumPrac]
a = tab
s = S-enter
d = C-backspace
f = backspace

[CapsLayer:C]
j = left
k = down
l = up
; = right
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
- = f11
= = f12
m = home
/ = end
i = pagedown
o = pageup
f = backspace
r = delete
space = layer(control)
d = layer(shift)
s = layer(alt)
g = enter

[CapsLayer+control]
s = layer(alt)
d = layer(shift)

[CapsLayer+shift]
space = layer(control)
s = layer(alt)

[CapsLayer+alt]
d = layer(shift)
space = layer(control)

[CapsLayer+control+shift]
s = layer(alt)

[CapsLayer+control+alt]
d = layer(shift)

[CapsLayer+shift+alt]
space = layer(control)

[CapsLayer+control+shift+alt]

[LayoutLayer]
q = toggle(QWERTY)
w = toggle(NoCapsLayer)
e = toggle(NumPrac)
```

</details>

**Comment by rvaiya** [comment]
> Although alternating between repeating C-z and C-y can't be done instantly (such as the "sweeping" effect I showed in the vid a few comments back) by holding and releasing d while capslock+b is held and instead requires releasing and holding some keys...

From what I can see from your config, what you have described is expected behaviour, though it i possible I have not understood something. If you think there is a bug in the macro logic, I would appreciate it if you could create a dedicated issue and provide the minimal steps to reproduce it.

> As a side issue, I added macro_timeout = 250 and macro_repeat_timeout = 20 to my default.conf to try matching what appears in xset q, and I think the repeat timeout isn't actually reached. A

Please read the manpage carefully. The keyd options mean different things and are measured in different units.

I am treating this issue as closed for now since the original problem has been resolved.

**Comment by i-c-u-p** [comment]
>Edit 2: The timeout issue has been fixed.

Tested and it's indeed fixed for macro() and macro2() after updating to 49f863c.
