### ISSUE TITLE
Mapping custom acer key into usable Function Key

### ISSUE THREAD

**Issue by HeroCod** [rvaiya/keyd#865]
Hello!

I'm currently fighting teeth and nails with my installation of ubuntu over an acer predator helios neo 16 (PHN16-72) in trying to remap the custom predatorsense key into a usable keybind

So far I've managed to track down using `sudo journalctl -f` that besides not showing any input in `xev`, it throws an error `keyd[132179]: ERROR: unsupported evdev code: 0x1a9` when pressed

So here I am, in trying to figure out if I can use keyd to remap an unsupported key over to a supported keycode (such as making if press F13 or others)

Is there anyone here who successfully managed to remap an unsupported evdev code into something more usable?

NB: The reason I've added all of the buzzwords at the beginning is that there exists close to no articles in how to do so, especially with this laptop, and this way, if anyone had to have the same issue as me, they could find it.

**Comment by rvaiya** [comment]
This should be fixed by 79136f2a1

**Comment by HeroCod** [comment]
Unfortunately the error is still present and peeking into journalctl still returns keyd[1326]: ERROR: unsupported evdev code: 0x1a9

Is there any feedback I can provide to try and fix this?

**Comment by Nekotekina** [comment]
@HeroCod Hello, can you test my fork?
https://github.com/Nekotekina/keyd
I updated latest commit just now.

**Comment by rvaiya** [comment]
@HeroCod Can you post the full log? Are you sure you are running the tip of master?
